# Generated by Django 5.1.4 on 2025-12-11 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=255)),
                ('numero_client', models.CharField(max_length=20)),
                ('localisation_client', models.CharField(max_length=255)),
                ('type_commande', models.CharField(choices=[('CITYPROP', 'Cityprop'), ('CLIMATISEUR', 'Climatiseur'), ('TAPISPROP', 'Tapisprop')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CityClimaDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_intervention', models.DateField(blank=True, null=True)),
                ('satisfaction', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO_RET', 'KO - Retouche'), ('KO_REFUS', 'KO - Refus seconde intervention')], max_length=20, null=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.commande')),
            ],
        ),
        migrations.CreateModel(
            name='TapisDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ramassage', models.DateField(blank=True, null=True)),
                ('nombre_tapis', models.PositiveIntegerField()),
                ('cout', models.PositiveIntegerField()),
                ('date_traitement', models.DateField()),
                ('date_livraison', models.DateField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('NON_RESPECTE', 'Délai non respecté'), ('PRET', 'Tapis prêt'), ('CLIENT_INDISPO', 'Tapis prêt mais client indisponible'), ('LIVRE', 'Livraison effectuée')], default='NON_RESPECTE', max_length=30)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.commande')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
