# Generated by Django 5.1.4 on 2025-12-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_commande_cityclimadetails_tapisdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tapisdetails',
            name='date_livraison',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tapisdetails',
            name='date_traitement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
