# Generated by Django 5.1.4 on 2025-12-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_tapisdetails_date_livraison_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tapisdetails',
            name='cout',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tapisdetails',
            name='nombre_tapis',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
