# Generated by Django 5.1.4 on 2025-12-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_tapisdetails_cout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityclimadetails',
            name='fidelise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tapisdetails',
            name='fidelise',
            field=models.BooleanField(default=False),
        ),
    ]
