# Generated by Django 5.1.4 on 2025-12-12 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_cityclimadetails_fidelise_tapisdetails_fidelise'),
    ]

    operations = [
        migrations.CreateModel(
            name='FidelisationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('detail_city_clima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.cityclimadetails')),
                ('detail_tapis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.tapisdetails')),
            ],
        ),
    ]
