# Generated by Django 5.1.4 on 2025-12-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_fidelisationnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tapisdetails',
            name='statut',
            field=models.CharField(choices=[('NON_RESPECTE', 'Délai non respecté'), ('PRET', 'Tapis prêt'), ('CLIENT_INDISPO', 'Tapis prêt mais client indisponible'), ('LIVRE', 'client satisfait'), ('LIVRE', 'client insatisfait')], default='NON_RESPECTE', max_length=30),
        ),
    ]
