# Generated by Django 5.1.4 on 2025-12-12 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_tapisdetails_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='TapisAlerteCommentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tapis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_alerte', to='gestion.tapisdetails')),
            ],
        ),
    ]
