# Generated by Django 5.1.4 on 2025-12-15 17:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_tapisalertecommentaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('DEVIS', 'Devis'), ('FACTURE', 'Facture')], default='DEVIS', max_length=20)),
                ('numero_document', models.CharField(blank=True, max_length=50)),
                ('date_emission', models.DateField(default=django.utils.timezone.now)),
                ('lieu_emission', models.CharField(default='Abidjan', max_length=255)),
                ('objet', models.CharField(blank=True, max_length=255)),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.commande')),
            ],
        ),
        migrations.CreateModel(
            name='FactureLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=0, max_digits=12)),
                ('note_prix_unitaire', models.CharField(blank=True, max_length=255)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='gestion.facture')),
            ],
        ),
    ]
