# Generated by Django 5.1.4 on 2025-12-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_facture_factureligne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factureligne',
            name='prix_unitaire',
            field=models.PositiveIntegerField(),
        ),
    ]
