# Generated by Django 5.1.4 on 2025-12-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_alter_factureligne_prix_unitaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='montant_final_net',
            field=models.IntegerField(default=0, verbose_name='Montant Net à Payer'),
        ),
        migrations.AddField(
            model_name='facture',
            name='taux_reduction_pourcentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Réduction (%)'),
        ),
    ]
