# Generated by Django 5.1.4 on 2025-12-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_facture_montant_final_net_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tapisdetails',
            name='statut',
            field=models.CharField(choices=[('NON_RESPECTE', 'Délai non respecté'), ('PRET', 'Tapis prêt'), ('CLIENT_INDISPO', 'Tapis prêt mais client indisponible'), ('LIVRE-satisfait', 'client satisfait'), ('LIVRE-insatisfait', 'client insatisfait'), ('ABANDON', 'Tapis abandonné')], default='NON_RESPECTE', max_length=30),
        ),
    ]
