# Generated by Django 5.1.4 on 2025-12-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_alter_tapisdetails_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='fidelisationnote',
            name='fidelise_marquee',
            field=models.BooleanField(default=False),
        ),
    ]
