# Generated by Django 5.1.4 on 2025-12-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_alter_tapisdetails_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='signature',
            field=models.CharField(default='LA COMPTABILITÉ', max_length=255),
        ),
        migrations.AlterField(
            model_name='facture',
            name='taux_reduction_pourcentage',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7, verbose_name='Réduction (%)'),
        ),
    ]
