# Generated by Django 5.1.4 on 2025-12-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_alter_facture_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tapisdetails',
            name='statut',
            field=models.CharField(choices=[('NON_RESPECTE', 'En cours'), ('PRET', 'Tapis prêt'), ('CLIENT_INDISPO', 'Client indisponible'), ('LIVRE_SATISFAIT', 'Livré - Client satisfait'), ('LIVRE_INSATISFAIT', 'Livré - Client insatisfait'), ('ABANDON', 'Tapis abandonné')], default='NON_RESPECTE', max_length=30),
        ),
    ]
