# Generated by Django 5.1.4 on 2025-12-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_alter_tapisdetails_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tapisdetails',
            name='statut',
            field=models.CharField(choices=[('NON_RESPECTE', 'En cours'), ('PRET', 'En attente'), ('CLIENT_INDISPO', 'Tapis prêt Client indisponible'), ('LIVRE_SATISFAIT', 'Livré - Client satisfait'), ('LIVRE_INSATISFAIT', 'Livré - Client insatisfait'), ('ABANDON', 'Tapis abandonné')], default='NON_RESPECTE', max_length=30),
        ),
    ]
