# Generated by Django 5.1.4 on 2025-12-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_alter_tapisdetails_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('equipe', models.CharField(max_length=100, verbose_name='Équipe / Bénéficiaire')),
                ('libelle', models.CharField(max_length=255, verbose_name="Libellé de l'opération")),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée (Recette)'), ('SORTIE', 'Sortie (Dépense)')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('solde_historique', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
            ],
            options={
                'verbose_name': 'Opération de Caisse',
                'verbose_name_plural': 'Opérations de Caisse',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
