# Generated by Django 5.1.4 on 2025-12-25 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_operationcaisse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationcaisse',
            options={'ordering': ['date', 'id'], 'verbose_name': 'Opération de Caisse', 'verbose_name_plural': 'Opérations de Caisse'},
        ),
    ]
