# Generated by Django 5.1.4 on 2026-01-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_alter_operationcaisse_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityclimadetails',
            name='designation',
            field=models.TextField(blank=True, null=True, verbose_name='Désignation des équipements'),
        ),
        migrations.AddField(
            model_name='cityclimadetails',
            name='prestation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type de prestation'),
        ),
    ]
