# Generated by Django 5.1.4 on 2026-01-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_cityclimadetails_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tapisdetails',
            name='date_prevue_livraison',
            field=models.DateField(blank=True, null=True, verbose_name='Date prévue de livraison'),
        ),
    ]
