# Generated by Django 5.1.4 on 2026-01-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_tapisdetails_date_prevue_livraison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityclimadetails',
            name='prestation',
        ),
        migrations.AddField(
            model_name='cityclimadetails',
            name='cout',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Coût'),
        ),
    ]
