# Generated by Django 5.1.4 on 2026-01-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0023_remove_cityclimadetails_prestation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='numero_client',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tapisdetails',
            name='statut',
            field=models.CharField(choices=[('NON_RESPECTE', 'En cours(en Atelier)'), ('PRET', 'En attente(Sortie Atelier)'), ('CLIENT_INDISPO', 'Tapis prêt Client indisponible'), ('LIVRE_SATISFAIT', 'Livré - Client satisfait'), ('LIVRE_INSATISFAIT', 'Livré - Client insatisfait'), ('ABANDON', 'Tapis abandonné')], default='NON_RESPECTE', max_length=30),
        ),
    ]
