# Generated by Django 5.1.4 on 2026-01-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0024_alter_commande_numero_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityclimadetails',
            name='satisfaction',
            field=models.CharField(blank=True, choices=[('OK', 'OK - client satisfait'), ('KO_RET', 'KO - client accepte Retouche'), ('KO_REFUS', 'KO - Refus seconde intervention')], max_length=20, null=True),
        ),
    ]
